import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import { Toaster } from "sonner";
import SideBar from "@/components/sidebar";
import { Input } from "@/components/ui/input";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors />

        <div className="flex h-screen">
          <SideBar />
          <div className="login-bg w-full">
            <Input className="w-full h-[50px]" />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
