import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import { Toaster } from "sonner";
import SideBar from "@/components/sidebar";
import NavBar from "@/components/nav";
import AppInitializer from "./AppInitializer";
import { getMe } from "@/actions/get-me";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await getMe();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors />
        <AppInitializer user={data}>
          <div className="flex">
            <div className="hidden md:block">
              <SideBar />
            </div>
            <div className="w-screen relative">
              <NavBar />
              <div className="pt-20 max-w-[1500px] my-0 mx-auto md:pl-64 mb-5">
                {children}
              </div>
            </div>
          </div>
        </AppInitializer>
      </body>
    </html>
  );
}
